url: http://sidneylimafilho.com.br
name: O blog do Sidney Filho
description: A página pessoal do Sidney
destination: _site
permalink: /:categories/:title
markdown: kramdown
exclude: [make.cmd, .nojekyll, CNAME]
